name: Crear una Instancia EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: Aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{  secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: lanzar instancia EC2
        run: |
          aws ec2 run-instances \
            --image-id ami-0cd0d9843545b1c77 \
            --count 1 \
            --instance-type t2.micro \
            --key-name ihf-EC2-LN \
            --security-group-ids sg-06d84ba602546e697 \
            --subnet-id subnet-0f347f31b78298a59 \
            --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=MiEC2byGithubActions}]'