name: Crear una Instancia EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: Aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{  secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: lanzar instancia EC2
        run: |
          aws ec2 run-instances \
            --image-id ${{ vars.AWS_AMI_ID }} \
            --count 1 \
            --instance-type ${{ vars.AWS_TIPO_INSTANCIA }} \
            --key-name ${{ secrets.AWS_KEY_NAME }} \
            --security-group-ids ${{ secrets.AWS_SECURITY_GROUP_ID }} \
            --subnet-id ${{ secrets.AWS_SUBNET_ID }} \
            --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=MiEC2byGithubActions}]'